### ISSUE TITLE
Inability to resolve a feed causes crash in the program

### ISSUE THREAD

**Issue by alecisec** [PromoFaux/MattermostRSS#2]
Using pre-built container promofaux/mattermostrss
following the container logs (docker logs -f MattermostRSS)
this is what I'm seeing before the container restarts:
```

Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred 
while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at MattermostRSS.Program.GetRssFeed(String url) in /source/MattermostRSS/Program.cs:line 130
   at MattermostRSS.Program.ProcessRssFeeds(RssFeed rssFeed) in /source/MattermostRSS/Program.cs:line 71
   at MattermostRSS.Program.Main(String[] args) in /source/MattermostRSS/Program.cs:line 48

```
This also means the most recent post from RSS is re-posted in the mattermost channel leading to the channel endlessly filling with repeated content.

**Comment by alecisec** [comment]
Should also note that the issue is intermittent and may be the result of an unreliable network however I need it to fail safer than this to avoid spamming the channel.

**Comment by PromoFaux** [comment]
Probably sloppy coding on my part! Will take a look at this later, thanks for the report!

**Comment by alecisec** [comment]
Is there a way that I can easily debug to determine which feed is causing the crash? (i.e. verbose logging) Currently I'm limited to wiresharking or removing the feeds from the json config one by one.

**Comment by alecisec** [comment]
I've at least identified the feed that's crashing the application - it's public if you'd like to add it to a sample setup and troubleshoot https://www.auscert.org.au/rss/bulletins/

**Comment by PromoFaux** [comment]
I'm unable to reproduce this with the feed you (previously) linked, but you have reminded me that I need to make this a bit more robust. It works for what it works for, but what happens with the "unknowns" is anyone's guess. I originally designed this just for parsing a Reddit RSS feed, but figured it could probably be extended to other feeds. 

Something I noticed with the auscert feed is that I currently only get one post out of it, due to the character limit on MM, rather than truncate the incoming webhook, it just chucks it away!

Currently the easiest way to debug is to run it in Visual Studio 2017 with docker installed and go from there. I'll try and work on making the logging a bit better.

**Comment by PromoFaux** [comment]
Actually, I think the issue of re-posts is down to my docker naivety, specifically around permissions..

**Comment by PromoFaux** [comment]
Yep, I was right.

Ignore the `-e PUID`/`-e GUID` settings on the `docker run` command. They do nothing... This was my first attempt at working with Docker. In order to stop the repetition of old posts, you need to ensure that your `docker` user has write access to the directory containing `secrets.json`

**Comment by alecisec** [comment]
Yup I actually worked out that there was other issues and that removing the auscert feed (hence removing the previous post) still resulted in the same errors. I'm not using the -e settings (skipped them straight away) I can confirm that i'm getting write access for the .json but it still re-posts because the process terminates before creating the "LastProcessedItem" timestamp. I've posted my updated json here https://pastebin.com/dfRvjPq6

**Comment by alecisec** [comment]
I should also note that while I was having similar issues with bitbackofen's mattermost RSS container theirs would simply skip unreadable posts. For these trivial news articles that's less of an issue.

**Comment by PromoFaux** [comment]
Thanks, I'll take a look at some of these feeds tomorrow.

Some of the skipping may be down to the 4000 char limit on mattermost incoming webhooks.  I've been working on the [mattermost webhook client](https://github.com/PromoFaux/Matterhook.NET.MatterhookClient) part of that this evening to get around that limit.

For now.. sleep time!

**Comment by alecisec** [comment]
Sorry, without access to visual studio or a verbose logging system I can't really be more specific in reporting this issue.

**Comment by PromoFaux** [comment]
@alecisec I've made some changes on the development branch, and tested them with your `secrets.json` (including the AusCert feed) and it appears to be processing them fine.

Can you give it a go your end and see? Just pushed an image tagged `development` to docker cloud.

I think I may have to add in an option to truncate very long messages. Currently, with the latest changes to `Matterhook.NET.MatterhookClient`, messages with text length >3800 are split into multiple messages. This is fine if a post will be split into two or three different messages, but with some of the feeds you have in your config, I've seen it go as high as 22 messages! Could get a bit spammy. The important feedback I need for now though, is whether or not your initial issue is solved... 

TODO: Logging

**Comment by PromoFaux** [comment]
PS

This one did not work, see if you can spot why 😉 

```JSON
    {
      "FeedPretext": "Krebs on Security",
      "Url": "https://pbs.twimg.com/profile_images/667033512403476480/HPSTaLj2_200x200.png",
      "BotChannelOverride": "",
      "BotNameOverride": "Brian Krebs",
      "BotImageOverride": "https://krebsonsecurity.com/wp-content/uploads/2009/11/krebsinbelgium.png",
      "FeedType": "",
      "LastProcessedItem": "0001-01-01T00:00:00"
    },
```

**Comment by PromoFaux** [comment]
Update: `development` tag now includes the ability to enable or disable showing the content.

Just add `"IncludeContent": false` to each `RssFeeds[]` item that you wish to supress  (defaults to true if not set) You will still get the title/link to article

**Comment by PromoFaux** [comment]
For what it's worth, I think the issue you've reported should be resolved by https://github.com/PromoFaux/MattermostRSS/commit/1626ffbf51c558890cceeec750cb38eb4a855353.

I was only trapping for errors with the Xml when getting the feed, when I should also have been trapping HTTP errors. Please test using the latest `development` image on docker hub

**Comment by PromoFaux** [comment]
Should be fixed in 1.1, which I've just released.

@alecisec I've made a couple of minor changes to the configuration layout, so check your config file before trying it!

Please feel free to reopen this issue or start a new one if you have any more issues

**Comment by alecisec** [comment]
I thought it was resolved with the new code but it seems I'm still having issues. The errors I'm seeing now are 

`Problem retrieving feed
 Exception Message: Data at the root level is invalid. Line 1, position 1.
One or more errors occurred. (Object reference not set to an instance of an object.)
`
And although the log output from the container now shows which feed was being processed at the time the error occurred it doesn't seem to be consistently correct. The container no longer halts when an error occurs however it does not continue to process subsequent feeds in the config (Which I've re-written in line with the changed format).

Some great changes here though, I notice the formatting on secrets.json no longer gets stripped making it possible to change the running config much more easily.

I've been experimenting with adding one feed a time but I seem to run into this error on a random feed which was otherwise working fine once I add about the 4th or 5th feed. I'll keep trying to figure out a more accurate description of the conditions to recreate the issue.

**Comment by alecisec** [comment]
I suspect the AusCERT feed still doesn't work - no errors but the process just halts when scraping the site. The URL for that one was https://www.auscert.org.au/rss/bulletins/

**Comment by alecisec** [comment]
I'm noticing whichever feed causes the issue-  when I look at the config the LastProcessedItem will have a Z appended to the end of the line e.g. ""LastProcessedItem": "2017-10-05T02:27:59Z"" sometimes with a space preceding the Z ""LastProcessedItem": "2017-10-05T02:27:59 Z" this is the only consistency between which feed causes the 'loop' of processing to restart
